language: python

python:
  - 2.7
  - 3.4
  - 3.5

install:
  - pip install -r test_requirements.txt
  - pip install -q coverage pytest-cov pytest-flakes
  - python setup.py -q install

script:
    - py.test test_pocket.py --cov responses --cov-report term-missing --flakes
